**`¿qué atributos describen una fase?`**    
el modelo va aprender sobre los atributos de la fase.  

**`¿cómo se agrupan esas fases dentro de familias?`**     
no he de trabajar con fase - máquina sino más bien familias de fases - máquinas.   

**`revisar los tiempos reales`**      
puede haber mucho ruido y he de controlarlo.   

**`construir la tabla de conteo`**
conteo de familias de fases x máquinas

atributos → familias → tabla de conteos familia × máquina → lectura de dónde hay decisión

In [1]:
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [7]:
ruta_OF = os.path.join("res", "CPRManufacturingOrder.csv")
ruta_FASE = os.path.join("res", "CPRMOTask.csv")
print(ruta_OF)
print(ruta_FASE)

res\CPRManufacturingOrder.csv
res\CPRMOTask.csv

In [14]:
df_OF = pd.read_csv(ruta_OF, encoding="utf-8", sep=";", header=0)
df_FASE = pd.read_csv(ruta_FASE, encoding="utf-8", sep=";", header=0)

display(df_OF) 
display(df_FASE)

C:\Users\jaume\AppData\Local\Temp\ipykernel_19648\445536750.py:1: DtypeWarning: Columns (0: NULL) have mixed types. Specify dtype option on import or set low_memory=False.
  df_OF = pd.read_csv(ruta_OF, encoding="utf-8", sep=";", header=0)
C:\Users\jaume\AppData\Local\Temp\ipykernel_19648\445536750.py:2: DtypeWarning: Columns (0: NULL.16, 1: NULL.17, 2: NULL.18, 3: NULL.22) have mixed types. Specify dtype option on import or set low_memory=False.
  df_FASE = pd.read_csv(ruta_FASE, encoding="utf-8", sep=";", header=0)

,000744d2-5b9e-40be-9126-9a8a66954f33,100,OF2502249,921ac292-f882-47f8-ae0b-ce82c4f1a3c8,9e856d02-3287-4b00-b968-3e6625ce343a,CONDUCTEUR 103127410,2,d3bd7234-a0af-4c35-b658-dcd8ac943c67,<p>A1</p>,7.0000000000,...,JMAU,7.0000000000.1,153b2e67-a636-4e4f-9fa5-fc100da76dfb,NULL.4,2025-03-05 10:50:29.903,ICRE,NULL.5,NULL.6,622d3b9e-0ddb-4f25-9cee-4a75a8043531,0.2
0,0008c8eb-104f-4631-8a7c-50b6d1166cc4,100,OF2509130,6b526dff-7ba3-4251-99fb-96ff8a71d6eb,5e9a3901-79f9-48fa-b4fd-57fbf86aa663,Elektrodenschaft F704510502739,2,d3bd7234-a0af-4c35-b658-dcd8ac943c67,<p>EXP</p>,3.0,...,JMAU,3.0,153b2e67-a636-4e4f-9fa5-fc100da76dfb,NaN,2025-09-10 08:57:03.283,MLOP,NaN,NaN,b6a24aba-a057-4f68-8d94-aeeedc5162c8,0
1,00099e2e-ced0-4712-9485-07458a7c7136,200,OF2600720,3105656a-9b07-481d-bf0c-408929a367a4,fb7a3acf-d6d7-4ffa-96aa-4030ad099820,CENTRADOR FPP08KXEM,2,ac03c504-f4d6-45ef-a1a4-69d9349feba9200,NaN,10.0,...,DGUI,10.0,153b2e67-a636-4e4f-9fa5-fc100da76dfb200,NaN,2026-03-04 16:32:45.627,DLEO,NaN,NaN,269ba198-6477-4740-b3a8-b9ef1da5b89e,0
2,000be0da-5295-42a4-87cf-bf7036f5df2d,100,OF2602948,86a77194-ec9d-4c80-aeea-4631abab94d6,06525099-59f0-4a6d-bde6-5ecc9bf94502,Mangon 6028003,2,d3bd7234-a0af-4c35-b658-dcd8ac943c67,NaN,2.0,...,JMAU,2.0,153b2e67-a636-4e4f-9fa5-fc100da76dfb,NaN,2026-04-07 12:29:28.057,SBRU,NaN,NaN,aed7f840-e511-4430-8117-ea89d3989a68,0
3,00111737-d13f-4c82-86c2-995751c98724,100,OF2600425,bb09abb1-6458-4db9-8dfb-18031995ffb0,50b248db-4711-41e8-a2c3-9ffd3e487193,BRAS 250610101,2,d3bd7234-a0af-4c35-b658-dcd8ac943c67,NaN,1.0,...,JMAU,1.0,153b2e67-a636-4e4f-9fa5-fc100da76dfb,NaN,2026-01-19 14:08:40.610,MCAS,NaN,NaN,NaN,0
4,0012ec1d-b5c2-476f-9e5a-7c5d37622253,100,OF2503768,c24ba629-5257-43a8-a0cb-0a0b70e4dc1f,eeae5b5f-4358-4b8d-b602-592ed7da7200,Portaelectrodes Xapa D1062000,2,d3bd7234-a0af-4c35-b658-dcd8ac943c67,NaN,1.0,...,JMAU,1.0,153b2e67-a636-4e4f-9fa5-fc100da76dfb,NaN,2025-04-07 19:28:35.907,BPUI,NaN,NaN,5f8b4814-841a-4796-ae8b-3fc91d9c70b7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20653,fff1ac7a-bace-4e9d-88f3-9a63c52aac11,100,OF2601737,0a4fc895-4b0e-45e0-821c-90cde095eb02,2547391e-bf97-4ac6-b0a6-8d8fcbccf3bf,Pol positiu-negatiu 7223301252012,2,d3bd7234-a0af-4c35-b658-dcd8ac943c67,NaN,15.0,...,JMAU,15.0,153b2e67-a636-4e4f-9fa5-fc100da76dfb,NaN,2026-03-09 15:23:17.877,AFER,NaN,NaN,97d549ff-1edf-4c1d-8011-033f2b86c67d,0
20654,fff665e4-c75e-4df6-8312-f03bce66bca1,100,OF2509824,6cbc9f8f-a5b1-47ca-9a6f-983b99684c23,b33009d2-2dda-480c-9a85-ff92835e13b7,SOPORTE GUIA PINFI-0503-B00-00000,2,d3bd7234-a0af-4c35-b658-dcd8ac943c67,NaN,4.0,...,JMAU,4.0,153b2e67-a636-4e4f-9fa5-fc100da76dfb,NaN,2025-09-30 14:10:31.080,SBRU,NaN,NaN,8c2e69c7-8d9d-4882-a53e-6a2cb266ab6d,0
20655,fff9976b-2041-4d97-a58b-626fdd391d93,100,OF2501158,d2ec0129-d0aa-4812-a6ec-3cadbdd0cb9d,a2e7a9e9-51a3-475e-93d0-e997b3783a36,Previ pinola D63.5 /// No fer stock//,2,d3bd7234-a0af-4c35-b658-dcd8ac943c67,NaN,4.0,...,JMAU,4.0,153b2e67-a636-4e4f-9fa5-fc100da76dfb,NaN,2025-02-11 16:39:59.347,BPUI,NaN,NaN,2f845653-b72a-4f1b-ab44-2e47b14ab883,0
20656,fffa6544-e9f9-418e-80d8-ed2aab02c49d,100,OF2606235,6258526e-aa6d-46a5-905a-cf3e07fbb551,0958a599-5576-4028-852f-1d15ea85ae17,Portaelectrodes MD153346R,2,d3bd7234-a0af-4c35-b658-dcd8ac943c67,NaN,2.0,...,JMAU2,2.0,153b2e67-a636-4e4f-9fa5-fc100da76dfb,NaN,2026-07-23 07:12:59.390,SBRU,NaN,NaN,65f671cf-ae5a-4a35-981d-cbbd8ff4ded9,0
20657,fffe5cf7-6bae-449a-b15f-aa41b56a6f71,100,OF2606118,e3c10431-5362-40e2-a2a1-f326a74adb52,8f0c306e-ebf6-484c-b2ad-4a48c357073d,Flexible 7076401250008,2,d3bd7234-a0af-4c35-b658-dcd8ac943c67,<p>PECES EN STOCK - NOM&Eacute;S FALTA FRESAR</p>,7.0,...,AHAB,7.0,153b2e67-a636-4e4f-9fa5-fc100da76dfb,NaN,2026-07-21 09:20:31.477,JMAU,NaN,NaN,030b3bd8-eaed-42c9-8785-32595e08d99c,0

,00003219-f775-4bea-9e04-dbafb6e8fd80,100,7de89fb9-e8db-48bf-b822-9c52431c44a1,07,Marcatges,NULL,7,1,1.1,0,...,0.20,0.21,0.0000000000.2,0.22,NULL.22,0.0000000000.3,1.0000000000.1,0.23,1.10,4
0,00016084-d562-4609-8501-3a761ca0351b,100,83c754de-86e0-4ec0-bf8b-c25d7a03fc3b,03,Marcatges,NaN,15,2,0,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,1
1,0001b76c-daef-40a0-ab87-b634f1cf52ca,100,8a44da1e-e189-44f4-89c4-e4787480d008,01,Preparació de material,NaN,5,5,0,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,1
2,0001bec0-dea7-4b62-9676-7357a8644b50,100,5f23162f-cebd-40bb-98e8-78a3628c6b0f,06,Preparació de material,NaN,5,5,0,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,1
3,0001c0de-53ea-4dd2-ace5-d7f0a16ed8ef,100,c307dbec-03fb-4c15-977d-81945a2ff960,09,Conformats,NaN,20,8,50,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,1
4,00024bf1-6b5c-4aa9-9056-b551a5dab700,100,4c1863be-c065-47fa-a492-d058890824e9,08,Verificació manual,NaN,8,0,0,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131568,fffd0aad-6be9-4061-9af4-38cce2ac6d1c,100,f3c0cd71-b0fe-4703-902b-719db3e8dff6,TA007,Acabats,NaN,7,1,15,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,1
131569,fffd0f13-b968-425c-a763-79b142c20a41,100,cc6095d5-47c3-4eb0-be3c-523bfe289ead,04,Mecanitzat al Torn Puma Petit,NaN,20,5,25,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,4
131570,fffd40d2-7299-4db6-9211-c15d496f9a9f,100,31f445e6-8160-467f-96cb-6ee0c018ca0a,01,Preparació de material,NaN,5,5,0,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,1
131571,ffff66a3-391d-43e7-b52f-e1ebc03ff16b,100,1200c5a6-98d2-4ac6-96a2-0c4d91c3c274,TA005,Mecanització a TCN,NaN,10,0,0,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,1
131572,ffff8364-507b-4431-b587-afbedf5e1d85,100,e2de8c4f-3815-423b-b4b5-c29b7d5f904a,02,Programació TCN,NaN,10,30,0,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,4

In [13]:
display(df_FASE.head())

,00003219-f775-4bea-9e04-dbafb6e8fd80,100,7de89fb9-e8db-48bf-b822-9c52431c44a1,07,Marcatges,NULL,7,1,1.1,0,...,0.20,0.21,0.0000000000.2,0.22,NULL.22,0.0000000000.3,1.0000000000.1,0.23,1.10,4
0,00016084-d562-4609-8501-3a761ca0351b,100,83c754de-86e0-4ec0-bf8b-c25d7a03fc3b,03,Marcatges,NaN,15,2,0,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,1
1,0001b76c-daef-40a0-ab87-b634f1cf52ca,100,8a44da1e-e189-44f4-89c4-e4787480d008,01,Preparació de material,NaN,5,5,0,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,1
2,0001bec0-dea7-4b62-9676-7357a8644b50,100,5f23162f-cebd-40bb-98e8-78a3628c6b0f,06,Preparació de material,NaN,5,5,0,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,1
3,0001c0de-53ea-4dd2-ace5-d7f0a16ed8ef,100,c307dbec-03fb-4c15-977d-81945a2ff960,09,Conformats,NaN,20,8,50,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,1
4,00024bf1-6b5c-4aa9-9056-b551a5dab700,100,4c1863be-c065-47fa-a492-d058890824e9,08,Verificació manual,NaN,8,0,0,0,...,0,0,0.0,0,NaN,0.0,1.0,0,1,4